# Generated by Django 4.1.7 on 2023-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuisineType',
            field=models.TextField(choices=[('', ''), ('American', 'American'), ('Asian', 'Asian'), ('British', 'British'), ('Caribbean', 'Caribbean'), ('Central Europe', 'Central Europe'), ('Chinese', 'Chinese'), ('Eastern Europe', 'Eastern Europe'), ('French', 'French'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Kosher', 'Kosher'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Middle Eastern', 'Middle Eastern'), ('Nordic', 'Nordic'), ('South American', 'South American'), ('South East Asian', 'South East Asian')], default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='dishType',
            field=models.TextField(choices=[('', ''), ('biscuits and cookies', 'biscuits and cookies'), ('bread', 'bread'), ('cereals', 'cereals'), ('condiments and sauces', 'condiments and sauces'), ('desserts', 'desserts'), ('drinks', 'drinks'), ('main course', 'main course'), ('pancake', 'pancake'), ('preps', 'preps'), ('preserve', 'preserve'), ('salad', 'salad'), ('sandwiches', 'sandwiches'), ('side dish', 'side dish'), ('soup', 'soup'), ('starter', 'starter'), ('sweets', 'sweets')], default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='mealType',
            field=models.TextField(choices=[('', ''), ('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack'), ('teatime', 'teatime')], default=''),
        ),
    ]
